### ISSUE TITLE
.anb files arent converted with anb_extract

### ISSUE THREAD

**Issue by Garganold** [leamsii/Shovel-Knight-Packer#10]
When dragging the anb file i only get the error:

Log: Extracting 1 frames..
Error: Could not convert raw pixels to image. Width: 64, Height: 64
 not enough image data
Exiting in 5 seconds..

**Comment by leamsii** [comment]
Can you send me the .anb file?

**Comment by Garganold** [comment]
https://gofile.io/?c=eTgxof
Here is the link
