### ISSUE TITLE
"Something wen't wrong" when unpacking anb

### ISSUE THREAD

**Issue by blargsnarf** [leamsii/Shovel-Knight-Packer#5]
I managed to unpack a .pak file, but when I go to unpack the .anb within, I get this error: [https://i.imgur.com/rX0vA9X.png](url)

Log: Decompressing WFLZ chunks..
Log: Cleaning up..
Log: Creating images..
Error: Something wen't wrong when converting the image frame_0.png 16777215 12

I think I have Python and Pillow installed properly. I've tried a few different anb files.

**Comment by leamsii** [comment]
Can you send me a sample file, the anb file

**Comment by blargsnarf** [comment]
> Can you send me a sample file, the anb file
> […](#)
> On Tue, Dec 10, 2019, 6:49 PM blargsnarf ***@***.***> wrote: I managed to unpack a .pak file, but when I go to unpack the .anb within, I get this error: https://i.imgur.com/rX0vA9X.png <http://url> Log: Decompressing WFLZ chunks.. Log: Cleaning up.. Log: Creating images.. Error: Something wen't wrong when converting the image frame_0.png 16777215 12 I think I have Python and Pillow installed properly. I've tried a few different anb files.

Sure thing:
https://www.dropbox.com/s/9huwvy8hfa2wk0e/cardMaster.anb?dl=0

Also worth noting is if I run it from a directory that has spaces in it (i was trying to run it from E:/Game Stuff/shovelknight) it gets as far as Game and then breaks.

But even moving it to a root folder (in this case E:/shvknght) returns this "something wen't wrong" error.

Hopefully it's just me installed python/pillow wrong - let me know if it works for you.

**Comment by leamsii** [comment]
Found out what the problem is, this particular file has slightly different offsets for its image width and height and threw the whole thing off. I'm soon going to be updating this tool to be more efficient and easier to use, but for now here are the images.
[CardMaster.zip](https://github.com/leamsii/Shovel-Knight-Toolkit/files/3953265/CardMaster.zip)

**Comment by blargsnarf** [comment]
That's great, I'm glad it's something solvable.

Unfortunately I tried it with a lot of different paks/anbs, and they all returned the same error... paks work fine, but none of the anbs extract. The game did just update yesterday, so maybe they changed something with the general offsets.

Regardless, looking forward to an updated version, a lot of the new areas have some really beautiful sprites and it'd be great to take a look at them.

**Comment by leamsii** [comment]
Thank you for letting me know

**Comment by leamsii** [comment]
Updated the tool to work with the newer version of SK, sprite swapping functionality will later be added.
