### ISSUE TITLE
terminate called after throwing an instance of 'std::out_of:range'

### ISSUE THREAD

**Issue by blargsnarf** [leamsii/Shovel-Knight-Packer#6]
I hate making another issue window, but now I'm getting a different error :(.

Error printscreen: https://i.imgur.com/ZLjIT5F.png

Full text:
Log: Extracting frames..
terminate called after throwing an instance of 'std::out_of:range'
  what(): basic_string::substr:  __pos (which is 18446744073709551615) > this->size() (which is 6)

Again, .pak extracted fine, but .anb did not.

Pak used: https://www.dropbox.com/s/egcnczgygmpwtr1/kingNPC.pak?dl=0
Anb used: https://www.dropbox.com/s/9qo2wv8so191gut/kingKnightMom.anb?dl=0

I tried it with a bunch of different paks (and anbs), and always the same error.

**Comment by leamsii** [comment]
Something else may have changed. Can test it on the first anb file you sent
me? I know it works there

**Comment by leamsii** [comment]
Actually no, It works on my PC, must be your PC environment, what OS are you running?
[KnightKnightMom.zip](https://github.com/leamsii/Shovel-Knight-Toolkit/files/3960835/KnightKnightMom.zip)

**Comment by blargsnarf** [comment]
Win7 64
Running this version of Python: https://www.python.org/downloads/release/python-380/
Installed pip thru that installer
Then installed pillow via cmd -> pip install pillow

Apologies if I'm still doing something wrong.

**Comment by leamsii** [comment]
Is no problem, this helps me with debugging. Python 3.8 is fairly new , not
sure if this is whats causing the issue, I updated the tool redownload it
from the Gitpage and let me know if you're still crashing

**Comment by blargsnarf** [comment]
Great, it now works, so long as the anb file is in the same folder as anb_extract.py. The pak file can be dragged in from a different folder, but anb still gives the same error if drug from another folder.

However, yeah, putting them all in the same folder works! Thanks so much, these sprites are great.

**Comment by leamsii** [comment]
Haha great thank you for helping with the debugging, I'll be fixing that
folder location issue in the near future.

**Comment by MonoJelly1** [comment]
I'm experiencing this same issue currently, Windows 10 64-Bit, Python 3.8.0, Pillow installed through pip.
Putting the anb files in the same folder as the anb_extract.py hasn't resolved the issue for me, unfortunately.

Log: Extracting frames..
terminate called after throwing an instance of 'std::out_of_range'
  what():  basic_string::substr: __pos (which is 18446744073709551615) > this->size() (which is 26)

**Comment by blargsnarf** [comment]
Do you have an older python still installed? I had to completely remove all older python versions, then reinstall just 3.8 (and then pillow, through cmd install pip pillow) for it to work.

**Comment by leamsii** [comment]
I'm looking into this now, It might have to do with spaces in your file names.

**Comment by leamsii** [comment]
I think I fixed the issue MonoJelly, mind downloading the updated tool and trying again. Let me know if it works. You too blarg. File names with spaces shouldn't be a problem now.

**Comment by MonoJelly1** [comment]
The newest update has corrected the issue for me, I seem to be able to extract anb files perfectly fine now.
Thank you for all of your work on this toolkit!

**Comment by blargsnarf** [comment]
Can confirm, saving the extractor to my normal "Art Stuff" folder _and_ dragging stuff in from other folders now both work.

Thanks so much for all the hard work on this!

**Comment by leamsii** [comment]
Great news ! Thank you guys for helping me debug this . Feel free to open any other issues .
