### ISSUE TITLE
ANB extractor doesn't work

### ISSUE THREAD

**Issue by MegAmi24** [leamsii/Shovel-Knight-Packer#8]
The anb extractor does nothing when opened. Dragging and dropping an anb file onto it will open a Python command window, but it terminates immediately after. I've tried multiple anb files and they all result in nothing.

Pak files and the unpacker work fine.

**Comment by leamsii** [comment]
Can you run the script through command line and send a screenshot of what error it says

**Comment by MegAmi24** [comment]
> Can you run the script through command line and send a screenshot of what error it says

Oddly enough, the tool actually worked when run through a command line. Dragging and dropping just doesn't work.

**Comment by leamsii** [comment]
I'll look into it thank you

**Comment by leamsii** [comment]
Fixed
