### ISSUE TITLE
Can't unpack .pak files

### ISSUE THREAD

**Issue by HowealTankaa** [leamsii/Shovel-Knight-Packer#9]
When drag & dropping .pak files from the game data (ver 4.0) i get "Impossible to start execution. The argument list is too long" (approximative traduction from french btw).

Did I do something wrong or does it has to do with the latest version of the game? (I'm here to get the sprites from player king knight as i couldn't get them on https://www.spriters-resource.com/pc_computer/shovelknight  so maybe someone already tried idk)

**Comment by leamsii** [comment]
Can you take a screenshot ? Also attach the .pak file.

**Comment by HowealTankaa** [comment]
[Uploading Unpacking Problem.zip…]()

**Comment by HowealTankaa** [comment]
Idk if it worked so here it is on drive: 
https://drive.google.com/drive/folders/1gMpT--kTbJLmmHtkIU1OeEoCbR0t6gZE?usp=sharing

**Comment by leamsii** [comment]
You have Python installed right ? Can you run it through command prompt without drag drop

**Comment by HowealTankaa** [comment]
What should i put in the prompt?

**Comment by HowealTankaa** [comment]
>>> os.chdir('C:\\Users\\octav\\Desktop\\Shovel-Knight-Toolkit-master')
>>> os.getcwd()
'C:\\Users\\octav\\Desktop\\Shovel-Knight-Toolkit-master'
>>> ppacker.py
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
NameError: name 'ppacker' is not defined
>>> ppacker.py kingPlayer.pak
  File "<stdin>", line 1
    ppacker.py kingPlayer.pak
               ^
SyntaxError: invalid syntax



I tried this based on the other issue where DnD didnt work, but it doesnt seem to work either

**Comment by leamsii** [comment]
There's something wrong with your Python environment set-up

**Comment by ManApart** [comment]
When I run through command line I also get an issue; it's probably my python environment as well, as I don't do much python.

```
λ python --version
Python 3.5.2

λ pip install Pillow
Requirement already satisfied: ...

λ python ppacker.py airshipTable.pak
  File "ppacker.py", line 40
    print(f"Log: Extracting {len(file_names)} files..")
                                                     ^
SyntaxError: invalid syntax
```
